# **Introduction to Python**

Python is a versatile and powerful programming language. It's known for its readability and simplicity, making it an excellent choice for beginners and professionals alike.


---

## Variables and Data Types
Variables are used to store information that can be referenced and manipulated in a program. Python supports various data types such as integers, floats, strings, and booleans.

In [ ]:
print("Hello! Today is a great day to learn python")

Hello! Today is a great day to learn python

In [ ]:
var = 10
print (var)
var = 20
rav = 30
print(var, rav)

10
20 30

In [ ]:
1==2

False

In [ ]:
# print(1 == 2)

print(1 == 2)

1 == 1

False

True

In [ ]:
type(1==1)

bool

In [ ]:
type('anshaj')

str

In [ ]:
type(1.1)

float

In [ ]:
# Integer variable
age = 30
print(f'Age: {age} (Type: {type(age)})')

# Float variable
height = 5.75
print(f'Height: {height} (Type: {type(height)})')

# String variable
name = "John Doe"
print(f'Name: {name} (Type: {type(name)})')

# Boolean variable
is_student = True # False
print(f'Is student: {is_student} (Type: {type(is_student)})')

Age: 30 (Type: <class 'int'>)
Height: 5.75 (Type: <class 'float'>)
Name: John Doe (Type: <class 'str'>)
Is student: True (Type: <class 'bool'>)

In [ ]:
True

True

## Arithmetic Operators
Arithmetic operators are used to perform mathematical operations. Here are some examples:

In [ ]:
# Arithmetic operators examples
a = 10
b = 5
print(f'Addition: {a} + {b} = {a + b}')
print(f'Subtraction: {a} - {b} = {a - b}')
print(f'Multiplication: {a} * {b} = {a * b}')
print(f'Division: {a} / {b} = {a / b}')
print(f'Modulus: {a} % {b} = {a % b}') # Modulo -> Remainder
print(f'Exponentiation: {a} ** {b} = {a ** b}')

Addition: 10 + 5 = 15
Subtraction: 10 - 5 = 5
Multiplication: 10 * 5 = 50
Division: 10 / 5 = 2.0
Modulus: 10 % 5 = 0
Exponentiation: 10 ** 5 = 100000

In [ ]:
print(f"{first_name} is a new student at {high_school}")

NameError: name 'first_name' is not defined

In [ ]:
template = "{first_name} is a new student at {high_school}"

In [ ]:
1 == 2

template.format(first_name = "John", high_school = 'Fresh high school')

False

In [ ]:
template.format(first_name = "Alice", high_school = 'XYZ High school')

'Alice is a new student at XYZ High school'

## Comparison Operators
Comparison operators are used to compare values. Here are some examples:

In [ ]:
# Comparison operators examples
x = 10
y = 20
print(f'{x} == {y}: {x == y}')  # Equal to
print(f'{x} != {y}: {x != y}')  # Not equal to
print(f'{x} > {y}: {x > y}')    # Greater than
print(f'{x} < {y}: {x < y}')    # Less than
print(f'{x} >= {y}: {x >= y}')  # Greater than or equal to
print(f'{x} <= {y}: {x <= y}')  # Less than or equal to

10 == 20: False
10 != 20: True
10 > 20: False
10 < 20: True
10 >= 20: False
10 <= 20: True

## Logical Operators
Logical operators are used to combine conditional statements. Here are some examples:

In [ ]:
email_template = "Hi {employee_name} This is to inform you that our company policies are changing..."

In [ ]:
email_template.format(employee_name = "Nirmal")

'Hi Nirmal This is to inform you that our company policies are changing...'

In [ ]:
email_template.format("Praful")

'Hi Praful This is to inform you that our company policies are changing...'

In [ ]:
print(1,2,3,4,5,6, "Hello")

1 2 3 4 5 6 Hello

In [ ]:
# Logical operators examples
p = True
q = False
print(f'p and q: {p and q} of the type {type(p and q)}')  # Logical AND
print(f'p or q: {p or q}')    # Logical OR
print(f'not p: {not p}')      # Logical NOT

p and q: False of the type <class 'bool'>
p or q: True
not p: False

## Strings
Strings are sequences of characters. They are used to represent text in a program. Strings in Python are enclosed within either single quotes (`'`) or double quotes (`"`).

In [ ]:
# String examples
greeting = 'Hello, World!'
print(greeting)
message = "Python is fun!"
print(message)

Hello, World!
Python is fun!

## Methods in Strings
Python provides various methods to manipulate strings. Here are some commonly used string methods:

In [ ]:
# String methods examples
text = "Hello, Python!"
print(text.lower())    # Convert to lowercase
print(text.upper())    # Convert to uppercase
print(text.replace("Python", "World"))  # Replace substring
# print(text.split(", "))  # Split the string

hello, python!
HELLO, PYTHON!
Hello, World!

In [ ]:
sentence = 'Today is a great day to learn python! And the holidays are almost upon us'

In [ ]:
split_sentence = sentence.split()
split_sentence

['Today',
 'is',
 'a',
 'great',
 'day',
 'to',
 'learn',
 'python!',
 'And',
 'the',
 'holidays',
 'are',
 'almost',
 'upon',
 'us']

In [ ]:
split_sentence[0]

'Today'

In [ ]:
split_sentence[1]

'is'

In [ ]:
split_sentence

['Today', 'is', 'a', 'great', 'day', 'to', 'learn', 'python!']

In [ ]:
type(split_sentence)

list

In [ ]:
" ".join(split_sentence)

'Today is a great day to learn python! And the holidays are almost upon us'

In [ ]:
"-+".join(split_sentence)

'Today-+is-+a-+great-+day-+to-+learn-+python!-+And-+the-+holidays-+are-+almost-+upon-+us'

In [ ]:
sentence_2 = 'Today is a great day to learn python. I am learning python. I am going to have fun'

In [ ]:
split_sentence = sentence_2.split(".")

In [ ]:
type(split_sentence)

list

In [ ]:
".".join(split_sentence)

'Today is a great day to learn python. I am learning python. I am going to have fun'

# **Python Data Structures**
In this notebook, we will cover various data structures in Python including lists, tuples, sets, and dictionaries. We will also explore some common methods and operations for each of these data structures.

## Lists
Lists are ordered collections of items. Lists are mutable, meaning their contents can be changed. Here are some common methods and operations you can perform on lists.

In [ ]:
# List examples
fruits = ['apple', 'banana', 'cherry']
print(fruits)

# Append an item to the list
fruits.append('orange')
print(fruits)

# Remove an item from the list
fruits.remove('banana')
print(fruits)

# Accessing list elements
print(fruits[0]) # First item
print(fruits[1])  # Second item
print(fruits[-1]) # Last item

['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry', 'orange']
['apple', 'cherry', 'orange']
apple
cherry
orange

In [ ]:
fruits = ['apple', 'banana', 'cherry', 'watermelon','Pear', 'Mango', 'Blueberry', 'Strawberry']

In [ ]:
fruits[-3]

'Mango'

In [ ]:
fruits

['apple', 'cherry', 1, 1.1, True, [1, 2, 3, 4], 'orange']

In [ ]:
fruits[0]

'apple'

In [ ]:
fruits[-1]

'orange'

In [ ]:
fruits[-3]

True

## Slicing in Python
Slicing is used to access a range of elements in a list or a string. Here are some examples:

In [ ]:
numbers = [10, 20, 30, 40, 50,  60, -20, -10, 5, 8, 5, 65]
numbers

[10, 20, 30, 40, 50, 60, -20, -10, 5, 8, 5, 65]

In [ ]:
numbers[0] = 1000
numbers

[1000, 20, 30, 40, 50, 60, -20, -10, 5, 8, 5, 65]

In [ ]:
numbers[4:7]

[50, 60, -20]

In [ ]:
numbers[-5:-2]

[-10, 5, 8]

In [ ]:
numbers[1: 9:2]

[20, 40, 60, -10]

In [ ]:
numbers[-8:-2:2]

[50, -20, 5]

In [ ]:
# Slicing lists
numbers = [10, 20, 30, 40, 50,  60, -20, -10, 5, 8, 5, 65]


# Starting index is always included
# Ending index is always exluded

numbers[-5:-2]

# print(numbers[2:5])   # Elements from index 2 to 4
# print(numbers[ : 3])    # First three elements
# print(numbers[5:  ])    # Elements from index 5 to the end
# print(numbers[-3:])   # Last three elements

# Slicing strings
# text = 'June 1st 2025 is today!'
# print(text[7:12])    # Characters from index 7 to 11
# # print(text[:5])      # First five characters
# # print(text[7:])      # Characters from index 7 to the end
# print(text[-6:])     # Last six characters

[60, -20, -10]

## Joining and Splitting Lists
The `join` method is used to convert a list into a string, and the `split` method is used to split a string into a list. Here are some examples:

In [ ]:
# Join a list into a string
words = ['Python', 'is', 'fun']
sentence = ' '.join(words)
print(sentence)

# Split a string into a list
text = 'Python is fun'
word_list = text.split(' ')
print(word_list)

Python is fun
['Python', 'is', 'fun']

## Tuples
Tuples are ordered collections of items, similar to lists. However, tuples are immutable, meaning their contents cannot be changed.

In [ ]:
numbers
# numbers[0] = 5
# numbers

[5, 20, 30, 40, 50, 60, -20, -10, 5, 8]

In [ ]:
# Tuple examples
dimensions = (1920, 1080)
print(dimensions)
print(dimensions[0])
print(dimensions[1])

# Tuples are immutable
#dimensions[0] = 1280  # This will raise an error

(1920, 1080)
1920
1080

In [ ]:
dimensions[0] = 1280

TypeError: 'tuple' object does not support item assignment

In [ ]:
name = 'Anshaj'

In [ ]:
name[0:2]

'An'

In [ ]:
name[0] = 'V'

TypeError: 'str' object does not support item assignment

## Sets
Sets are unordered collections of unique items. They are mutable and allow for efficient membership testing.

In [ ]:
# Set examples
fruits = {'apple', 'banana', 'cherry'}
print(fruits)

# Add an item to the set
fruits.add('orange')
print(fruits)

# Update the set with multiple items
fruits.update(('mango', 'grape'))
print(fruits)

# # Remove an item from the set
fruits.remove('banana')

print(fruits)

fruits.add('orange')

fruits

{'banana', 'cherry', 'apple'}
{'banana', 'cherry', 'orange', 'apple'}
{'banana', 'grape', 'apple', 'cherry', 'mango', 'orange'}
{'grape', 'apple', 'cherry', 'mango', 'orange'}

{'apple', 'cherry', 'grape', 'mango', 'orange'}

In [ ]:
set_a = {1 , 1, 1, 2, 2, 2, 3 , 4, 5}

set_a

## Dictionaries
Dictionaries are collections of key-value pairs. They are unordered and mutable.

In [ ]:
# Dictionary examples
student = {
    'name': 'Alice',
    'age': 25,
    'courses': ['Math', 'CompSci'],
    'hobbies' : {
        'sports' : 'cricket',
        'music' : 'classical',
        'movies' : 'action'
    }
    }

print(student)

# Accessing dictionary values
print(student['name'])
print(student['age'])

# # Adding and updating dictionary values
student['age'] = 26

student['phone'] = 220266
print(student)

{'name': 'Alice', 'age': 25, 'courses': ['Math', 'CompSci'], 'hobbies': {'sports': 'cricket', 'music': 'classical', 'movies': 'action'}}
Alice
25
{'name': 'Alice', 'age': 26, 'courses': ['Math', 'CompSci'], 'hobbies': {'sports': 'cricket', 'music': 'classical', 'movies': 'action'}, 'phone': 220266}

In [ ]:
student['courses'][-1]

'CompSci'

In [ ]:
student['hobbies']['music']

'classical'

In [ ]:
student['hobbies']['music']

'classical'

In [ ]:
student['hobbies']['movies']

In [ ]:
student['hobbies']['music']

In [ ]:
student['job_interests'] = 'Python Programming'
student

{'name': 'Alice',
 'age': 26,
 'courses': ['Math', 'CompSci'],
 'hobbies': {'sports': 'cricket', 'music': 'classical', 'movies': 'action'},
 'phone': '555-5555',
 'job_interests': 'Python Programming'}

In [ ]:
student['grades']

KeyError: 'grades'

In [ ]:
student

In [ ]:
student.get('grades', "Unknown")

'Unknown'

In [ ]:
student.get("schooling_history", "Missing information")

'Missing information'

In [ ]:
student.get("courses", "Missing information")

['Math', 'CompSci']

In [ ]:
student

{'name': 'Alice',
 'age': 26,
 'courses': ['Math', 'CompSci'],
 'hobbies': {'sports': 'cricket', 'music': 'classical', 'movies': 'action'},
 'phone': '555-5555',
 'job_interests': 'Python Programming'}

In [ ]:
student.get('name', 'No key found')

'Alice'

In [ ]:
student.get('job_interests', 'Unknown')

'Python Programming'

# **Python Control Flow and Loops**
In this notebook, we will cover control flow statements and loops in Python, including if, if-else, if-elif, if-elif-else, loops, nested loops, break and continue statements, and functions.

## If Statements
The `if` statement is used to test a condition and execute a block of code if the condition is true.

In [ ]:
# If statement example
x = 10
if x > 5:
    print(f'{x} is greater than 5')
    print('Hello')
    print("This is being executed")

# if x == 'anshaj':
#   print("The value of x is anshaj")

# # if x == 10:
# #   print("X is 10")

10 is greater than 5
Hello
This is being executed

In [ ]:
month = 'May'

if month == 'December':
  print("It's christmas time")
elif month == 'January':
  print("Its so cold")
elif month == 'February':
  print("Its still super cold")
elif month == 'March':
  print("Maybe not so cold")
else:
  print("I don't know what month it is")

I don't know what month it is

In [ ]:
name = 'Sam'

if name == 'Anshaj':
  print("Anshaj is teaching this class")
else:
  print("You're a learner in today's session")

You're a learner in today's session

## If-Else Statements
The `if-else` statement is used to test a condition and execute one block of code if the condition is true, and another block of code if the condition is false.

In [ ]:
# If-else statement example
x = 10
if x > 15:
    print(f'{x} is greater than 15')
else:
    print(f'{x} is not greater than 15')

10 is not greater than 15

## If-Elif Statements
The `if-elif` statement is used to test multiple conditions. If the first condition is false, it checks the next condition, and so on.

In [ ]:
# If-elif statement example
x = -10
if x > 15:
    print(f'{x} is greater than 15')
elif x > 12:
  print(f'{x} is greater than 12')
elif x == 10:
  print("You've hit the jackpot")
elif x > 5:
    print(f'{x} is greater than 5 but not greater than 15')
else:
    print('x is probably less than 5')

## If-Elif-Else Statements
The `if-elif-else` statement is used to test multiple conditions and execute different blocks of code based on which condition is true.

In [ ]:
# If-elif-else statement example
x = 10
if x > 15:
    print(f'{x} is greater than 15')
elif x > 10:
    print(f'{x} is greater than 10 but not greater than 15')
elif x > 5:
    print(f'{x} is greater than 5 but not greater than 10')
else:
    print(f'{x} is not greater than 5')

10 is greater than 5 but not greater than 10

## Loops
Loops are used to execute a block of code multiple times. Python supports `for` and `while` loops.

### For Loops
The `for` loop is used to iterate over a sequence (such as a list, tuple, or string) and execute a block of code for each item in the sequence.

In [ ]:
# For loop example
fruits = ['apple', 'banana', 'cherry', 'oranges', 'watermelon','grapes','pear']

for fruit in fruits:
    if fruit == 'apple':
      print("I love eating apple")
    elif fruit == 'oranges':
      print("I like drinking orange juice instead")
    elif fruit == 'banana':
      print("Yay! Banana shake")
    else:
      print("Um, I would not like to eat this fruit")

I love eating apple
Yay! Banana shake
Um, I would not like to eat this fruit
I like drinking orange juice instead
Um, I would not like to eat this fruit
Um, I would not like to eat this fruit
Um, I would not like to eat this fruit

In [ ]:
for i in range(6):
  print(i)

0
1
2
3
4
5

In [ ]:
for i in range(1,4):
  print(i)

1
2
3

In [ ]:
for i in range(1,10,2):
  print(i)

1
3
5
7
9

In [ ]:
len(fruits)

6

In [ ]:
for i in range(6):
  print(i, fruits[i])

0 apple
1 banana
2 cherry
3 oranges
4 watermelon
5 grapes

In [ ]:
for i in range(len(fruits)):
  print(i, fruits[i])

0 apple
1 banana
2 cherry
3 oranges
4 watermelon
5 grapes

In [ ]:
for index, element in enumerate(fruits):
  print(index, element)

0 apple
1 banana
2 cherry
3 oranges
4 watermelon
5 grapes

### While Loops
The `while` loop is used to execute a block of code as long as a condition is true.

In [ ]:
# While loop example
current_students = 0

while current_students <= 30:
    print(f'There are {current_students} students in the class')
    current_students += 1
    print("New Student Admitted")

There are 0 students in the class
New Student Admitted
There are 1 students in the class
New Student Admitted
There are 2 students in the class
New Student Admitted
There are 3 students in the class
New Student Admitted
There are 4 students in the class
New Student Admitted
There are 5 students in the class
New Student Admitted
There are 6 students in the class
New Student Admitted
There are 7 students in the class
New Student Admitted
There are 8 students in the class
New Student Admitted
There are 9 students in the class
New Student Admitted
There are 10 students in the class
New Student Admitted
There are 11 students in the class
New Student Admitted
There are 12 students in the class
New Student Admitted
There are 13 students in the class
New Student Admitted
There are 14 students in the class
New Student Admitted
There are 15 students in the class
New Student Admitted
There are 16 students in the class
New Student Admitted
There are 17 students in the class
New Student Admitted
There are 18 students in the class
New Student Admitted
There are 19 students in the class
New Student Admitted
There are 20 students in the class
New Student Admitted
There are 21 students in the class
New Student Admitted
There are 22 students in the class
New Student Admitted
There are 23 students in the class
New Student Admitted
There are 24 students in the class
New Student Admitted
There are 25 students in the class
New Student Admitted
There are 26 students in the class
New Student Admitted
There are 27 students in the class
New Student Admitted
There are 28 students in the class
New Student Admitted
There are 29 students in the class
New Student Admitted
There are 30 students in the class
New Student Admitted

## Nested Loops
Nested loops are loops within loops. The inner loop is executed for each iteration of the outer loop.

In [ ]:
fruits

['apple', 'banana', 'cherry', 'oranges', 'watermelon', 'grapes', 'pear']

In [ ]:
deserts = ['brownie', 'icecream', 'cupcake']

In [ ]:
for fruit in fruits:
  for desert in deserts:
    if fruit == 'apple' and desert == 'icecream':
      print("This is a fantasic combination")
    elif fruit == 'cherry' and desert == 'cupcake':
      print("This is my second fav combination")
    else:
      print(f"Nah! {fruit} with {desert} is not fun!")

Nah! apple with brownie is not fun!
This is a fantasic combination
Nah! apple with cupcake is not fun!
Nah! banana with brownie is not fun!
Nah! banana with icecream is not fun!
Nah! banana with cupcake is not fun!
Nah! cherry with brownie is not fun!
Nah! cherry with icecream is not fun!
This is my second fav combination
Nah! oranges with brownie is not fun!
Nah! oranges with icecream is not fun!
Nah! oranges with cupcake is not fun!
Nah! watermelon with brownie is not fun!
Nah! watermelon with icecream is not fun!
Nah! watermelon with cupcake is not fun!
Nah! grapes with brownie is not fun!
Nah! grapes with icecream is not fun!
Nah! grapes with cupcake is not fun!
Nah! pear with brownie is not fun!
Nah! pear with icecream is not fun!
Nah! pear with cupcake is not fun!

In [ ]:
# Nested loops example
for i in range(3):
    for j in range(5):
        print(f'i = {i}, j = {j}')

i = 0, j = 0
i = 0, j = 1
i = 0, j = 2
i = 0, j = 3
i = 0, j = 4
i = 1, j = 0
i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 1, j = 4
i = 2, j = 0
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 2, j = 4

In [ ]:
count = 1

while count < 10:
  print("Count value", count)
  count += 1 # count = count + 1

Count value 1
Count value 2
Count value 3
Count value 4
Count value 5
Count value 6
Count value 7
Count value 8
Count value 9

## Break and Continue
The `break` statement is used to exit a loop prematurely, and the `continue` statement is used to skip the current iteration and proceed to the next iteration.

In [ ]:
fruits

['apple', 'banana', 'cherry', 'oranges', 'watermelon', 'grapes', 'pear']

In [ ]:
# Break example
for fruit in fruits:
  if fruit == 'oranges':
    print("Yuck! My taste buds are gone!")
    break
  print(fruit)

apple
banana
cherry
Yuck! My taste buds are gone!

In [ ]:
# Break example
for fruit in fruits:
  if fruit == 'oranges':
    print("Oranges are soo bad but you know what, I kinda like these ones, but I will never have them again")
    continue
  print(f"I love this fruit {fruit}")

I love this fruit apple
I love this fruit banana
I love this fruit cherry
Oranges are soo bad but you know what, I kinda like these ones, but I will never have them again
I love this fruit watermelon
I love this fruit grapes
I love this fruit pear

In [2]:
fruits = ['apple', 'banana', 'cherry', 'oranges', 'watermelon','grapes','pear']
fruits

['apple', 'banana', 'cherry', 'oranges', 'watermelon', 'grapes', 'pear']

In [3]:
for fruit in fruits:
  print(fruit)

apple
banana
cherry
oranges
watermelon
grapes
pear

In [16]:
len(fruits)

7

In [14]:
for i in range(len(fruits)):
  print(i, fruits[i]) # Second way of writing a for loop

0 apple
1 banana
2 cherry
3 oranges
4 watermelon
5 grapes
6 pear

In [17]:
for index, value in enumerate(fruits):
  print(index, value)

0 apple
1 banana
2 cherry
3 oranges
4 watermelon
5 grapes
6 pear

In [ ]:
for i in range(5):
    if i == 3:
        continue
    print(i)

0
1
2
4

In [ ]:
# Break example
for i in range(5):
    if i == 3:
        break
    print(i)

# Continue example
for i in range(5):
    if i == 3:
        continue
    print(i)

0
1
2
0
1
2
4

## Functions
Functions are reusable blocks of code that perform a specific task. They are defined using the `def` keyword.

In [18]:
def print_hello_new_year():
  print("Hello! New year is almost here")

In [19]:
print_hello_new_year()

Hello! New year is almost here

In [20]:
def find_interesting_fruits(fruits):

  interesting_fruits = []

  for fruit in fruits:
    if fruit == 'apple' or fruit == 'banana':
      interesting_fruits.append(fruit)

  return interesting_fruits

In [21]:
fruits

['apple', 'banana', 'cherry', 'oranges', 'watermelon', 'grapes', 'pear']

In [22]:
my_fav_fruits = find_interesting_fruits(fruits)
my_fav_fruits

['apple', 'banana']

In [23]:
def add_numbers(a, b):
  return a + b

In [24]:
add_numbers(5, 10)

15

In [25]:
def subtract_numbers(a, b):
  return a - b

In [26]:
subtract_numbers(10, 5)

5

In [27]:
subtract_numbers(a = 10, b = 5)

5

In [28]:
subtract_numbers(b = 10, a = 5) # Recommended practise

-5

In [ ]:
add_numbers('anshaj', 'khare')

'anshajkhare'

In [ ]:
# Function example
def greet(name):
    return f'Hello, {name}!'

# Call the function
print(greet('Alice'))
print(greet('Bob'))

Hello, Alice!
Hello, Bob!

In [ ]:
def add(a, b):
  return a + b

In [ ]:
add(50, 60) # positional arguments

110

In [ ]:
add(b=5, a=6) #keyword arguments

11

In [29]:
def add(a,b=0, c=0, d=0, e=0, f=0): # Not a scalable approach
  return a+b+c

In [32]:
add(5, 10, 15)

30

In [ ]:
add(d=10)

TypeError: add() got an unexpected keyword argument 'd'

In [ ]:
add(5, 6)

In [ ]:
add(5,6,7)

18

In [33]:
## Variable number of arguments

def add(*args):

  result = 0
  for value in args:
    result = result + value

  return result

In [37]:
add(1), add(2, 3), add(1,2,3,4,5,6,7,8,9,10,11)

(1, 5, 66)

In [ ]:
add(1), add(1,2), add(1,2,3), add(1,2,3,4,5,6,7,8)

(1, 3, 6, 36)

In [ ]:
add(1,2)

3

In [ ]:
add(1,2,3)

6

In [ ]:
add(1,2,3,4,5,6,7,8,9)

45

In [38]:
def get_basic_details(employee_id):
  mock_data = {
      1 : {"first_name": "Alex", 'occupation': 'Developer'},
      2 : {"first_name": "John", 'occupation': 'Manager'},
      3 : {"first_name": "Smith", 'occupation': 'HR'}
  }

  return mock_data.get(employee_id, "Employee not found")

In [44]:
get_basic_details(employee_id=3)

{'first_name': 'Smith', 'occupation': 'HR'}

In [46]:
get_basic_details(first_name='Alex')

TypeError: get_basic_details() got an unexpected keyword argument 'first_name'

In [49]:
def smart_employee_details(**kwargs):
  mock_data = {
      1 : {"first_name": "Alex", 'occupation': 'Developer'},
      2 : {"first_name": "John", 'occupation': 'Manager'},
      3 : {"first_name": "Smith", 'occupation': 'HR'}
  }

  if kwargs.get('employee_id'):
    return mock_data.get(kwargs.get('employee_id'), "Employee not found")
  elif kwargs.get('first_name'):
    for key, value in mock_data.items():
      if value.get('first_name') == kwargs.get('first_name'):
        return value
  else:
    return "Employee not found using your parameter"

In [48]:
smart_employee_details(employee_id=3)

{'first_name': 'Smith', 'occupation': 'HR'}

In [50]:
smart_employee_details(first_name='Alex')

{'first_name': 'Alex', 'occupation': 'Developer'}

In [51]:
smart_employee_details(random_parameter='xyz')

'Employee not found using your parameter'

In [ ]:
def print_employee_details(**kwargs):
  if 'salary' in kwargs:
    print("Employee data contains salary. Everything is good")
  else:
    print("This is a new employee. Please define their salary in the system")

In [ ]:
print_employee_details(x=10, xy=10)

This is a new employee. Please define their salary in the system

In [ ]:
print_employee_details(name ='John', lastname='Doe', age=10, salary='100k')

Employee data contains salary. Everything is good

In [ ]:
print_employee_details(firstname='John', lastname='Doe', age=10, department='finance')

This is a new employee. Please define their salary in the system

In [ ]:
employee_data = [{
    'name' : 'John',
    'age' : 30,
    'department' : 'HR',
    'stays_at' : ['Matrix', '1', 'value']
}]

In [ ]:
if employee_data.get('name') == 'John':
  employee_data['department'] = 'Sales'
employee_data

AttributeError: 'list' object has no attribute 'get'

In [ ]:
if employee_data.get('name') == 'Smith':
  print("Not gonna work")
employee_data

AttributeError: 'list' object has no attribute 'get'

In [ ]:
employee_data['name'] = 'Smith'

TypeError: list indices must be integers or slices, not str

In [ ]:
for key, value in employee_data.items():
  if key == 'name':
    employee_data['stays_at'] = 'Missing'

employee_data

AttributeError: 'list' object has no attribute 'items'

In [ ]:
def make_coffee(coffee_type, roast, drink='Americano'):
  pass

In [ ]:
def employee_details(**kwargs):
  # for key, value in kwargs.items():
  #   print(key, value)
  if "profession" in kwargs:
    call_the_spy_hr()
  else:
    call_normal_hr()

In [ ]:
employee_details(first_name='John', last_name = 'Wick', age = 40, profession = 'Spy')

NameError: name 'call_the_spy_hr' is not defined

In [ ]:
employee_details(occupation='Cook', location='New York')

NameError: name 'call_normal_hr' is not defined

In [ ]:
def print_employee_details(first_name, last_name, salary):
  pass

In [ ]:
def add_two_numbers(num_1: int, num_2: int) -> int:
  return num_1 + num_2

In [ ]:
add_two_numbers(3, 4)

7

In [ ]:
add_two_numbers(3.5, 4.5)

8.0

In [ ]:
add_two_numbers('Anshaj', "Khare")

'AnshajKhare'

In [ ]:
add_two_numbers()

TypeError: add_two_numbers() missing 2 required positional arguments: 'num_1' and 'num_2'

In [ ]:
def function_1():
  def nested_function_2(x):
    print(x)

  nested_function_2(10)

In [ ]:
function_1()

10

In [ ]:
lambda x: len(x)

# **Pandas Basics**

## Series

In [ ]:
import pandas as pd

In [ ]:
s1 = pd.Series([11, 21, 31, 5, 6, 7])

s1

0    11
1    21
2    31
3     5
4     6
5     7
dtype: int64

## DataFrame

In [ ]:
data = {'City': ['San Francisco', 'San Jose', 'Seattle'],
        'Population': [10000, 20000, 500000]}

df = pd.DataFrame(data)

df

            City  Population
0  San Francisco       10000
1       San Jose       20000
2        Seattle      500000

## Create a dataframe by reading data from a CSV file

In [52]:
import pandas as pd

csv_url = 'https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv'

In [ ]:
pd.read_

In [53]:
df = pd.read_csv(csv_url)

df.head(10) # read the first 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [54]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [55]:
type(df['Age'])

pandas.core.series.Series

In [56]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [57]:
type(df)

pandas.core.frame.DataFrame

In [60]:
df[['Age', 'Name', 'Survived']]

      Age                                               Name  Survived
0    22.0                            Braund, Mr. Owen Harris         0
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2    26.0                             Heikkinen, Miss. Laina         1
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1
4    35.0                           Allen, Mr. William Henry         0
..    ...                                                ...       ...
886  27.0                              Montvila, Rev. Juozas         0
887  19.0                       Graham, Miss. Margaret Edith         1
888   NaN           Johnston, Miss. Catherine Helen "Carrie"         0
889  26.0                              Behr, Mr. Karl Howell         1
890  32.0                                Dooley, Mr. Patrick         0

[891 rows x 3 columns]

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [62]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [63]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [65]:
df['Pclass'] == 1

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: Pclass, Length: 891, dtype: bool

In [66]:
df[df['Pclass'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [67]:
(df['Pclass'] == 1) & (df['Sex'] == 'female')

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Length: 891, dtype: bool

In [73]:
df[(df['Pclass'] == 1) & (df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [74]:
df.groupby('Pclass').agg({
    'Age' : 'mean',
    'Fare' : 'median'
})

              Age     Fare
Pclass
1       38.233441  60.2875
2       29.877630  14.2500
3       25.140620   8.0500

In [75]:
df.groupby('Pclass').agg({
    'Age' : ['mean', 'median', 'count', 'sum'],
    'Fare' : 'median'
})

              Age                           Fare
             mean median count      sum   median
Pclass
1       38.233441   37.0   186  7111.42  60.2875
2       29.877630   29.0   173  5168.83  14.2500
3       25.140620   24.0   355  8924.92   8.0500

In [ ]:
def compound_interest(principal, rate, time):
    return principal * (1 + rate) ** time

In [76]:
df.groupby(['Pclass', 'Sex']).agg({
    'Age' : 'mean',
    'Fare' : 'median',
    'Survived' : 'mean'
})

                     Age      Fare  Survived
Pclass Sex
1      female  34.611765  82.66455  0.968085
       male    41.281386  41.26250  0.368852
2      female  28.722973  22.00000  0.921053
       male    30.740707  13.00000  0.157407
3      female  21.750000  12.47500  0.500000
       male    26.507589   7.92500  0.135447

In [ ]:
df['Fare']

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [ ]:
df[['Age', 'Ticket']]

      Age            Ticket
0    22.0         A/5 21171
1    38.0          PC 17599
2    26.0  STON/O2. 3101282
3    35.0            113803
4    35.0            373450
..    ...               ...
886  27.0            211536
887  19.0            112053
888   NaN        W./C. 6607
889  26.0            111369
890  32.0            370376

[891 rows x 2 columns]

In [ ]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
df.groupby('Pclass').agg({
    'Age' : 'mean',
    'Fare' : 'mean'

})

              Age       Fare
Pclass
1       38.233441  84.154687
2       29.877630  20.662183
3       25.140620  13.675550

In [ ]:
df.groupby('Pclass').agg({
    'Age' : 'mean',
    'Fare' : 'mean',
    'Survived' : 'mean'
})

              Age       Fare  Survived
Pclass
1       38.233441  84.154687  0.629630
2       29.877630  20.662183  0.472826
3       25.140620  13.675550  0.242363

In [ ]:
df.groupby('Sex').agg({
    'Age' : 'mean',
    'Fare' : 'mean',
    'Survived' : 'mean'
})

              Age       Fare  Survived
Sex
female  27.915709  44.479818  0.742038
male    30.726645  25.523893  0.188908

In [ ]:
grouped_df = df.groupby(['Pclass','Sex']).agg({
    'Age' : 'mean',
    'Fare' : 'mean',
    'Survived' : 'mean'
})

In [ ]:
grouped_df.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th></th>\n      <th>Age</th>\n      <th>Fare</th>\n      <th>Survived</th>\n    </tr>\n    <tr>\n      <th>Pclass</th>\n      <th>Sex</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan="2" valign="top">1</th>\n      <th>female</th>\n      <td>34.611765</td>\n      <td>106.125798</td>\n      <td>0.968085</td>\n    </tr>\n    <tr>\n      <th>male</th>\n      <td>41.281386</td>\n      <td>67.226127</td>\n      <td>0.368852</td>\n    </tr>\n    <tr>\n      <th rowspan="2" valign="top">2</th>\n      <th>female</th>\n      <td>28.722973</td>\n      <td>21.970121</td>\n      <td>0.921053</td>\n    </tr>\n    <tr>\n      <th>male</th>\n      <td>30.740707</td>\n      <td>19.741782</td>\n      <td>0.157407</td>\n    </tr>\n    <tr>\n      <th rowspan="2" valign="top">3</th>\n      <th>female</th>\n      <td>21.750000</td>\n      <td>16.118810</td>\n      <td>0.500000</td>\n    </tr>\n    <tr>\n      <th>male</th>\n      <td>26.507589</td>\n      <td>12.661633</td>\n      <td>0.135447</td>\n    </tr>\n  </tbody>\n</table>'

## Filtering with `loc` and `iloc`

In [ ]:
# create a dataframe
data = {
    'Name': ['Lily', 'Emma', 'John'],
    'Age': [38, 35, 28],
    'Education': ['high shcool', 'phd', 'bachelor'],
    'Gender': [0, 0, 1]
}

customer = pd.DataFrame(data)

customer

   Name  Age    Education  Gender
0  Lily   38  high shcool       0
1  Emma   35          phd       0
2  John   28     bachelor       1

In [ ]:
# Let's use 'loc' method to select the first 2 rows and 'age', 'education' columns
customer.loc[0 : 1, ['Age', 'Education']]

# start row label : end row label
# start row inex : end row index (exclusive)

   Age    Education
0   38  high shcool
1   35          phd

In [ ]:
# Use iloc
customer.iloc[[0, 2],  [0, 1, 3]]

# # start row/column inex : end row/column index (exclusive)

   Name  Age  Gender
0  Lily   38       0
2  John   28       1

In [ ]:
customer

   Name  Age    Education  Gender
0  Lily   38  high shcool       0
1  Emma   35          phd       0
2  John   28     bachelor       1

In [ ]:
# select a column - education
customer['Education']

0    high shcool
1            phd
2       bachelor
Name: Education, dtype: object

In [ ]:
# select multiple columns - age, education
customer[['Age', 'Education']]

   Age    Education
0   38  high shcool
1   35          phd
2   28     bachelor

In [ ]:
customer.iloc[: ,  1:3]

   Age    Education
0   38  high shcool
1   35          phd
2   28     bachelor

In [ ]:
# based on a condition: Filter customers whose name is 'Lily'
filter = customer['Name'] == 'Lily'

customer_filtered1 = customer[filter]

customer_filtered1

   Name  Age    Education  Gender
0  Lily   38  high shcool       0

In [ ]:
customer_filtered2 = customer[customer['Name'] == 'Lily']

customer_filtered2

   Name  Age    Education  Gender
0  Lily   38  high shcool       0

In [ ]:
customer

   Name  Age    Education  Gender
0  Lily   38  high shcool       0
1  Emma   35          phd       0
2  John   28     bachelor       1

In [ ]:
# multile conditions: Age >= 35 and is female (0: female, 1: male)
filter = (customer['Age'] >= 35) & (customer['Gender'] == 0)

customer_filtered = customer[filter]

customer_filtered

   Name  Age    Education  Gender
0  Lily   38  high shcool       0
1  Emma   35          phd       0

In [ ]:
# filter the customer name starting with 'L' or 'E'
filter = customer['Name'].str.contains(r'^[L]', regex = True)

customer_filtered = customer[filter]

customer_filtered

   Name  Age    Education  Gender
0  Lily   38  high shcool       0

In [ ]:
name_list = ['Lily', 'John']

filter = customer['Name'].isin(name_list)

customer_filtered = customer[filter]

customer_filtered

   Name  Age    Education  Gender
0  Lily   38  high shcool       0
2  John   28     bachelor       1

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df['Ticket']

0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object

In [ ]:
df[['Age', 'Ticket']]

      Age            Ticket
0    22.0         A/5 21171
1    38.0          PC 17599
2    26.0  STON/O2. 3101282
3    35.0            113803
4    35.0            373450
..    ...               ...
886  27.0            211536
887  19.0            112053
888   NaN        W./C. 6607
889  26.0            111369
890  32.0            370376

[891 rows x 2 columns]

In [ ]:
df[['Age','Fare']]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [ ]:
# Filtering

df['Fare'] > 15

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888     True
889     True
890    False
Name: Fare, Length: 891, dtype: bool

In [ ]:
df[df['Fare'] > 15]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
df[df['Fare'] > 15]['Fare']

1      71.2833
3      53.1000
6      51.8625
7      21.0750
9      30.0708
        ...
880    26.0000
885    29.1250
887    30.0000
888    23.4500
889    30.0000
Name: Fare, Length: 433, dtype: float64

In [ ]:
(df['Fare'] > 15) & (df['Age'] < 40)

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Length: 891, dtype: bool

In [ ]:
df[(df['Fare'] > 15) & (df['Age'] < 40)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.sort_values('Age')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df.sort_values('Age', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df['Age'].dropna()

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
885    39.0
886    27.0
887    19.0
889    26.0
890    32.0
Name: Age, Length: 714, dtype: float64

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df['Age'].isna().sum()

np.int64(177)

In [ ]:
df['Age'].mean()

np.float64(29.69911764705882)

In [ ]:
df['Age'] = df['Age'].fillna(29.69)

In [ ]:
df['Age'].isna().sum()

np.int64(0)

## Sorting in a data frame

In [ ]:
data = {
    'Date': ['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04'],
    'Product': ['Product A', 'Product B', 'Product A', 'Product C'],
    'Quantity Sold': [100, 150, 120, 80],
    'Revenue': [5000, 7500, 6000, 4000]
}

# Create a DataFrame
df = pd.DataFrame(data)

df

         Date    Product  Quantity Sold  Revenue
0  2023-09-01  Product A            100     5000
1  2023-09-02  Product B            150     7500
2  2023-09-03  Product A            120     6000
3  2023-09-04  Product C             80     4000

In [ ]:
# See product from highest revenue to the lowest
df.sort_values(by = 'Revenue', ascending = False)

         Date    Product  Quantity Sold  Revenue
1  2023-09-02  Product B            150     7500
2  2023-09-03  Product A            120     6000
0  2023-09-01  Product A            100     5000
3  2023-09-04  Product C             80     4000

In [ ]:
# Sample DataFrame
data = {
    'Student_Name': ['Alice', 'Bob', 'Eve', 'David', 'Carol'],
    'Age': [25, 30, 22, 24, 28],
    'Score': [95, 93, 95, 88, 88]
}

df = pd.DataFrame(data)

df

  Student_Name  Age  Score
0        Alice   25     95
1          Bob   30     93
2          Eve   22     95
3        David   24     88
4        Carol   28     88

In [ ]:
df.sort_values(by = 'Score', ascending = False)

  Student_Name  Age  Score
0        Alice   25     95
2          Eve   22     95
1          Bob   30     93
3        David   24     88
4        Carol   28     88

In [ ]:
# Sort score from highest to the lowest, sort the student age from smallest to the largest
df.sort_values(by = ['Score', 'Age'] , ascending = [False, True])

  Student_Name  Age  Score
2          Eve   22     95
0        Alice   25     95
1          Bob   30     93
3        David   24     88
4        Carol   28     88